### ISSUE TITLE
building master

### ISSUE THREAD

**Issue by kaefert** [WeTheInternet/xapi#2]
Hi there! 

I cloned this repository using:
````git clone https://github.com/WeTheInternet/xapi.git````

running a buld results in this error for me:
````
[ERROR] /home/kaefert/Development/libs/xapi/core/api/src/main/java/xapi/dev/processor/AnnotationMirrorProcessor.java:[70,38] cannot find symbol
  symbol:   variable RELEASE_8
  location: class javax.lang.model.SourceVersion
````

<br\>
My motivation in building xapi is because I would like to use the xapi-gwt-reflect library with gwt 2.7.0
In the public maven repositories the latest release is 0.4 which seems to be only compatible with (up to?) GWT 2.5.1

Using it with GWT 2.6.0 or 2.6.1 or 2.7.0 gives error messages like this during gwt-compile:

Unable to read: jar:file:/.../gwt-user-2.6.1.jar!/com/google/gwt/*/*.gwtar. Skipping: java.io.InvalidClassException: com.google.gwt.dev.javac.CompiledClass; local class incompatible: stream classdesc serialVersionUID = 4010640329895161752, local class serialVersionUID = -522865011538185836

I've made sure that the xapi libraries come before the gwt libraries on my classpath, so that should not be the cause of my problems.

**Comment by JamesXNelson** [comment]
Hey @kaefert I recently released version 0.5 to maven central, and I believe I have also resolved to master build issue.  The Gwt fork is also in maven central, so there should not be any impediments now to checkout out and building the project.

If you have the time to try again, it would be surely appreciated!

**Comment by kaefert** [comment]
Good morning James! I'm happy to hear that you continued work on your xapi project!
At the moment I'm quite full, but in a week or two I'll test what you published and reply here again.

**Comment by JamesXNelson** [comment]
No problem! Hope all is well.  Let me know if I can be of any assistance.

**Comment by doggie1989** [comment]
@kaefert  @JamesXNelson 

I have tested version 0.5 in my project.
        providedCompile "net.wetheinter:xapi-gwt:0.5"
	providedCompile "net.wetheinter:gwt-user:2.7.0"
	providedCompile "net.wetheinter:gwt-dev:2.7.0"

We must use these 3 dependencies.

**Comment by kaefert** [comment]
Hey there James. Sorry that it took me much longer than I said, but now I'm gonna try again to replace the gwt-ent "2.0 RC1 GWT 2.3" release from July 2011 that only works up to GWT 2.6.1 with the reflection feature included in your xapi library.

First thing I tried (and failed) to do was build your xapi master branch.
```
[ERROR] Failed to execute goal on project xapi-gwt-api: Could not resolve dependencies for project net.wetheinter:xapi-gwt-api:jar:0.6-SNAPSHOT: Could not find artifact net.wetheinter:xapi-core-util:jar:sources:0.6-SNAPSHOT
```

**Comment by JamesXNelson** [comment]
Ahh, well, if you want, you can use the released 0.5 version.

However, if you have the lastest master, then I can only surmise that I forgot to force core-util to always produce a source jar.  I have been trying to get ./quickBuild.sh to be as fast as possible, but it looks like I should wipe out my repo to ensure that I am actually rebuilding all required source jars every time...  ./fullBuild.sh should produce the source jar you are missing, and then ./quickBuild.sh (mvn install) will work again.  

I generally use those scripts because they will run in parallel.  Much faster, though sometimes you have to give 'em a double-tap (run twice) if concurrency causes any issues. 

Anyway, sending -Dxapi.release=true tells the build to produce all source and docs.  I will patch it tonight to always build all required source jars, as that could lead to obscure bugs for people working on Gwt with sources jars.

**Comment by kaefert** [comment]
I've used ./fullBuild.sh

**Comment by gitgabrio** [comment]
Hi all, I can not find the version 0.5 on repository - where can I find it? I tried to clone the repository locally, but it seems I can not build it...

**Comment by JamesXNelson** [comment]
The last commit of 0.5 is https://github.com/WeTheInternet/xapi/commit/9a97459cdab8a83935d7faf85eecf3d79baf3b63

You can find that commit on the release tab:
https://github.com/WeTheInternet/xapi/releases/tag/xapi-0.5

However, be warned that 0.5 was not easily buildable; there were a few things kaefert discovered and I have fixed since then.  If you want to just use it, 0.5 is on maven central.  If you want to build it, you are encouraged to check out master.

**Comment by JamesXNelson** [comment]
I will likely release 0.6 after I rebase my gwt fork on top of the released gwt 2.8.

After that, release 0.7 will be all java 8 from the ground up, and I am going to be rebuilding the module structure to be compatible with the java 9 module system.  Most existing modules will still exist and be supported, but they may wind up moving in the source tree if it makes sense to do so. :-)

**Comment by gitgabrio** [comment]
Hi, sorry I was not clear with my question. What I meant is that I can not find 0.5 in MAVEN repository, nor Maven central. Probably I'm completely dumb, could you pleas post here the link? I have tried to inlucude the 0.5 dependency in my pom, but it is not resolved

<dependency>
        <groupId>net.wetheinter</groupId>
        <artifactId>xapi-gwt-reflect</artifactId>
        <version>0.5</version>
        </dependency>

Any help would be greatly appreciated :)

**Comment by kaefert** [comment]
http://mvnrepository.com/artifact/net.wetheinter

to use the xapi reflection you don't need xapi itself, but instead need to change the groupid of all your gwt dependencies (gwt-user, gwt-dev, gwt-codeserver, gwt-servlet) to net.wetheinter

**Comment by gitgabrio** [comment]
Many Thanks! Best
